# Generated by Django 2.2 on 2019-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_num_code', models.CharField(max_length=50)),
                ('country_alpha_1_code', models.CharField(max_length=50)),
                ('country_alpha_2_code', models.CharField(max_length=50)),
                ('country_name', models.TextField()),
                ('phone_prefix', models.IntegerField(default=0)),
                ('phone_length', models.IntegerField(default=0)),
            ],
        ),
    ]
